#!/bin/bash
  ec
  echo -e "    Incredible weather statistics from Gimlemoen"
  echo
  echo
  #figlet -t -c -f mono9 " $(curl -s http://gateway.hybel.csdnserver.com:8181/current.txt)$(echo -e "\xb0") "
  figlet -t -c -f mono9 " $(curl -s http://okarin/current.txt)$(echo -e "\xb0") "
  echo -e ""$DEF""
  ec
  echo -e "    Provided by Jonassen meterologiske institutt"
